import { WordPair } from './types';

export const wordlist: WordPair[] = [
  {"left":"Bad","right":"Good"},
  {"left":"Basic","right":"Hipster"},
  {"left":"Better hot","right":"Better cold"},
  {"left":"Mature","right":"Immature"},
  {"left":"Underrated weapon","right":"Overrated weapon"},
  {"left":"Hard to find","right":"Easy to find"},
  {"left":"Round","right":"Pointy"},
  {"left":"Trashy","right":"Classy"},
  {"left":"Optional","right":"Mandatory"},
  {"left":"Underpaid","right":"Overpaid"},
  {"left":"Dry","right":"Wet"},
  {"left":"Normal pet","right":"Exotic pet"},
  {"left":"Comedy","right":"Drama"},
  {"left":"Least evil company","right":"Most evil company"},
  {"left":"Unknown actor","right":"Famous actor"},
  {"left":"Easy to spell","right":"Hard to spell"},
  {"left":"Ugly man","right":"Beautiful man"},
  {"left":"Bad music","right":"Good music"},
  {"left":"Feels bad","right":"Feels good"},
  {"left":"Forbidden","right":"Encouraged"},
  {"left":"Rare","right":"Common"},
  {"left":"Smells bad","right":"Smells good"},
  {"left":"Star Wars","right":"Star Trek"},
  {"left":"Worst day of the year","right":"Best day of the year"},
  {"left":"Bad person","right":"Good person"},
  {"left":"Ethical to eat","right":"Unethical to eat"},
  {"left":"Movie","right":"Book"},
  {"left":"Action movie","right":"Adventure movie"},
  {"left":"Wisdom","right":"Intelligence"},
  {"left":"Hard to do","right":"Easy to do"},
  {"left":"Worthless","right":"Priceless"},
  {"left":"Nature","right":"Nurture"},
  {"left":"Dictatorship","right":"Democracy"},
  {"left":"Boring topic","right":"Fascinating topic"},
  {"left":"Conservative","right":"Liberal"},
  {"left":"Guilty pleasure","right":"Openly love"},
  {"left":"Skill","right":"Talent"},
  {"left":"Bad pizza topping","right":"Good pizza topping"},
  {"left":"Dystopia","right":"Utopia"},
  {"left":"Dark","right":"Light"},
  {"left":"Cheap","right":"Expensive"},
  {"left":"Popular","right":"Unpopular"},
  {"left":"Friend","right":"Enemy"},
  {"left":"Ugly","right":"Beautiful"},
  {"left":"Artisanal","right":"Mass-produced"},
  {"left":"Unhealthy","right":"Healthy"},
  {"left":"Harmful","right":"Helpful"},
  {"left":"Gryffindor","right":"Slytherin"},
  {"left":"Good","right":"Evil"},
  {"left":"Unbelievable","right":"Believable"},
  {"left":"Quiet place","right":"Loud place"},
  {"left":"Plain","right":"Fancy"},
  {"left":"Has a bad reputation","right":"Has a good reputation"},
  {"left":"Hot","right":"Cold"},
  {"left":"Normal thing to own","right":"Weird thing to own"},
  {"left":"Straight","right":"Curvy"},
  {"left":"Role model","right":"Bad influence"},
  {"left":"Underrated","right":"Overrated"},
  {"left":"Love","right":"Hate"},
  {"left":"The Light Side of the Force","right":"The Dark Side of the Force"},
  {"left":"Sad song","right":"Happy song"},
  {"left":"Dangerous job","right":"Safe job"},
  {"left":"Fantasy","right":"Sci-Fi"},
  {"left":"Non-partisan","right":"Partisan"},
  {"left":"Limited","right":"Infinite"},
  {"left":"Casual","right":"Formal"},
  {"left":"Mean person","right":"Nice person"},
  {"left":"Action","right":"Inaction"},
  {"left":"Villain","right":"Hero"},
  {"left":"Underrated thing to do","right":"Overrated thing to do"},
  {"left":"Tastes bad","right":"Tastes good"},
  {"left":"Sport","right":"Game"},
  {"left":"Unimportant","right":"Important"},
  {"left":"Easy to remember","right":"Hard to remember"},
  {"left":"Low quality","right":"High quality"},
  {"left":"Happens slowly","right":"Happens suddenly"},
  {"left":"Boring","right":"Exciting"},
  {"left":"Dog person","right":"Cat person"},
  {"left":"Introvert","right":"Extrovert"},
  {"left":"Book was better","right":"Movie was better"},
  {"left":"Needs a sequel","right":"Doesn't need a sequel"},
  {"left":"Bad actor","right":"Good actor"},
  {"left":"Dog name","right":"Cat name"},
  {"left":"Waste of time","right":"Good use of time"},
  {"left":"Scary animal","right":"Nice animal"},
  {"left":"Mainstream","right":"Niche"},
  {"left":"Dark","right":"Edgy"},
  {"left":"Talentless","right":"Talented"},
  {"left":"Temporary","right":"Permanent"},
  {"left":"Looks like a person","right":"Doesn't look like a person"},
  {"left":"Difficult to use","right":"Easy to use"},
  {"left":"Clean","right":"Dirty"},
  {"left":"Requires luck","right":"Requires skill"},
  {"left":"Flavorless","right":"Flavorful"},
  {"left":"Worst living person","right":"Greatest living person"},
  {"left":"Underrated movie","right":"Overrated movie"},
  {"left":"Messy","right":"Tidy"},
  {"left":"Pro-vaccine","right":"Anti-vaccine"},
  {"left":"Useless body part","right":"Useful body part"},
  {"left":"Fad","right":"Classic"},
  {"left":"Weak","right":"Strong"},
  {"left":"Disgusting food","right":"Delicious food"},
  {"left":"Better","right":"Worse"},
  {"left":"Stupid","right":"Brilliant"},
  {"left":"Artificial","right":"Natural"},
  {"left":"Art","right":"Commerce"},
  {"left":"One-hit wonder","right":"Pop icon"},
  {"left":"Bad habit","right":"Good habit"},
  {"left":"Cat person","right":"Dog person"},
  {"left":"Benefits you","right":"Benefits everyone"},
  {"left":"Worst athlete of all time","right":"Best athlete of all time"},
  {"left":"Sustenance","right":"Haute cuisine"},
  {"left":"Low-calorie","right":"High-calorie"},
  {"left":"Expected","right":"Unexpected"},
  {"left":"Authentic","right":" नकली (Fake)"},
  {"left":"Local issue","right":"Global issue"},
  {"left":"Illegal","right":"Legal"},
  {"left":"Normal","right":"Weird"},
  {"left":"Short","right":"Long"},
  {"left":"Colorless","right":"Colorful"},
  {"left":"Freedom","right":"Security"},
  {"left":"Powerless","right":"Powerful"},
  {"left":"Vice","right":"Virtue"},
  {"left":"Failure","right":"Masterpiece"},
  {"left":"Horizontal","right":"Vertical"},
  {"left":"Unpopular opinion","right":"Popular opinion"},
  {"left":"Friendship","right":"Romance"},
  {"left":"Unforgivable","right":"Forgivable"},
  {"left":"Replaceable","right":"Irreplaceable"},
  {"left":"Worst year in history","right":"Best year in history"},
  {"left":"Harmless","right":"Harmful"},
  {"left":"Traditional","right":"Radical"},
  {"left":"Bad investment","right":"Good investment"},
  {"left":"Socialist","right":"Capitalist"},
  {"left":"Analog","right":"Digital"},
  {"left":"The worst","right":"The best"},
  {"left":"Small talk","right":"Deep conversation"},
  {"left":"Inessential","right":"Essential"},
  {"left":"Ethical","right":"Unethical"},
  {"left":"Too small","right":"Too big"},
  {"left":"Crime","right":"Not a crime"},
  {"left":"Out of control","right":"Under control"},
  {"left":"Main character","right":"Side character"},
  {"left":"Useless invention","right":"Useful invention"},
  {"left":"Old fashioned","right":"Avant Garde"},
  {"left":"Bad president","right":"Good president"},
  {"left":"Sad movie","right":"Happy movie"},
  {"left":"Stinky in a good way","right":"Stinky in a bad way"},
  {"left":"Loved","right":"Hated"},
  {"left":"Not a sandwich","right":"A sandwich"},
  {"left":"Quiet","right":"Loud"},
  {"left":"Comedy","right":"Tragedy"},
  {"left":"Soft","right":"Hard"},
  {"left":"Necessity","right":"Luxury"},
  {"left":"Culturally significant","right":"Culturally insignificant"},
  {"left":"Useless major","right":"Useful major"},
  {"left":"Ordinary","right":"Extraordinary"},
  {"left":"80s","right":"90s"},
  {"left":"Bad man","right":"Good man"},
  {"left":"Well known fact","right":"Little known fact"},
  {"left":"Stupidest person alive","right":"Smartest person alive"},
  {"left":"Conventional","right":"Unconventional"},
  {"left":"Worst candy","right":"Best candy"},
  {"left":"Chaotic","right":"Lawful"},
  {"left":"Modest","right":"Arrogant"},
  {"left":"Theory","right":"Practice"},
  {"left":"Forgettable","right":"Memorable"},
  {"left":"Good for you","right":"Bad for you"},
  {"left":"Square","right":"Round"},
  {"left":"Ugly word","right":"Beautiful word"},
  {"left":"Easy subject","right":"Hard subject"},
  {"left":"Famous","right":"Infamous"},
  {"left":"Not huggable","right":"Huggable"},
  {"left":"Heterosexual","right":"Homosexual"},
  {"left":"Rough","right":"Smooth"},
  {"left":"Underrated book","right":"Overrated book"},
  {"left":"Bad advice","right":"Good advice"},
  {"left":"Religious","right":"Sacrilegious"},
  {"left":"Science","right":"Pseudoscience"},
  {"left":"Funny","right":"Not funny"},
  {"left":"Movie that Godzilla would ruin","right":"Movie that Godzilla would improve"},
  {"left":"Snack","right":"Meal"},
  {"left":"Job","right":"Career"},
  {"left":"Too short","right":"Too long"},
  {"left":"Peace","right":"War"},
  {"left":"Tastes good","right":"Tastes bad"},
  {"left":"Ugly woman","right":"Beautiful woman"},
  {"left":"Mental activity","right":"Physical activity"},
  {"left":"Unfashionable","right":"Fashionable"},
  {"left":"Happiness","right":"Sadness"},
  {"left":"Difficult to sit on","right":"Easy to sit on"},
  {"left":"Liberal Arts","right":"STEM"},
  {"left":"Person you could beat up","right":"Person who'd beat you up"},
  {"left":"Historically important","right":"Historically irrelevant"},
  {"left":"Hairless","right":"Hairy"},
  {"left":"Problem","right":"Solution"},
  {"left":"Tick","right":"Tock"},
  {"left":"Guilty","right":"Not guilty"},
  {"left":"Useless","right":"Useful"},
  {"left":"Deep thought","right":"Shallow thought"},
  {"left":"Nobody does it","right":"Everybody does it"},
  {"left":"Limp","right":"Firm"},
  {"left":"Bad superpower","right":"Good superpower"},
  {"left":"Old","right":"New"},
  {"left":"Boring person","right":"Interesting person"},
  {"left":"Worst era in history","right":"Best era in history"},
  {"left":"Fiction","right":"Non-fiction"},
  {"left":"Popular person","right":"Unpopular person"},
  {"left":"Sacred","right":"Profane"},
  {"left":"Truth","right":"Lie"},
  {"left":"Fragile","right":"Durable"},
  {"left":"Boring Hobby","right":"Exciting Hobby"},
  {"left":"Underrated Skill","right":"Overrated Skill"},
  {"left":"Easy to Cook","right":"Hard to Cook"},
  {"left":"Common Knowledge","right":"Obscure Fact"},
  {"left":"Bad Movie Sequel","right":"Good Movie Sequel"},
  {"left":"Normal thing to say on a first date","right":"Weird thing to say on a first date"},
  {"left":"Unreliable","right":"Reliable"},
  {"left":"Worst part of your day","right":"Best part of your day"},
  {"left":"Snack food","right":"Fine dining"},
  {"left":"Needs more salt","right":"Too much salt"},
  {"left":"Quiet animal","right":"Loud animal"},
  {"left":"Dystopian future","right":"Utopian future"},
  {"left":"Something you procrastinate on","right":"Something you do immediately"},
  {"left":"Cheap thrill","right":"Expensive hobby"},
  {"left":"Predictable plot","right":"Unpredictable plot"},
  {"left":"Common pet","right":"Exotic pet"},
  {"left":"Mildly annoying","right":"Infuriating"},
  {"left":"Something you'd find in a junk drawer","right":"Something you'd display proudly"},
  {"left":"Looks better in person","right":"Looks better in photos"},
  {"left":"Relaxing activity","right":"Stressful activity"},
  {"left":"Generic brand","right":"Designer brand"},
  {"left":"Bad advice","right":"Good advice"},
  {"left":"Light reading","right":"Heavy reading"},
  {"left":"Character you love to hate","right":"Character you just love"},
  {"left":"Temporary solution","right":"Permanent fix"}
];
